/*
-- Query: SELECT * FROM ofs.sys_menus
LIMIT 0, 1000

-- Date: 2020-03-25 14:01
*/
INSERT INTO `` (`ID`,`name`,`resource_id`,`parent_id`,`grade`,`path`,`component`,`title`,`permission`,`sort`,`icon`,`hidden`,`verification`,`description`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('63fb073973c54df7ad5fbc8eb883b775','string','string','string','1','string','string','string','string',1,'string','1','0','string','string','string','string','string');
INSERT INTO `` (`ID`,`name`,`resource_id`,`parent_id`,`grade`,`path`,`component`,`title`,`permission`,`sort`,`icon`,`hidden`,`verification`,`description`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('ecb7c9b0ecfc42369e1caa205fcd1723','测试新增',NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*
-- Query: SELECT * FROM ofs.sys_resource
LIMIT 0, 1000

-- Date: 2020-03-25 14:01
*/
INSERT INTO `` (`ID`,`code`,`name`,`permission`,`url`,`parent_id`,`type`,`description`,`create_date`,`update_date`,`create_user`,`update_user`,`sort`) VALUES ('1','sys','系统管理','sys','/sys','0','1',NULL,NULL,NULL,NULL,NULL,1);
INSERT INTO `` (`ID`,`code`,`name`,`permission`,`url`,`parent_id`,`type`,`description`,`create_date`,`update_date`,`create_user`,`update_user`,`sort`) VALUES ('127de9fad0504be7836b9288f196c3b9','testcode','测试新增','test:add','/test/url','0','2','测试数据',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ID`,`code`,`name`,`permission`,`url`,`parent_id`,`type`,`description`,`create_date`,`update_date`,`create_user`,`update_user`,`sort`) VALUES ('2','munus','菜单管理','menus','/sys/menus','1','1',NULL,NULL,NULL,NULL,NULL,1);
INSERT INTO `` (`ID`,`code`,`name`,`permission`,`url`,`parent_id`,`type`,`description`,`create_date`,`update_date`,`create_user`,`update_user`,`sort`) VALUES ('21cc1d30144b49d0a147566528f68a38',NULL,'测试新增',NULL,NULL,'0','1',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ID`,`code`,`name`,`permission`,`url`,`parent_id`,`type`,`description`,`create_date`,`update_date`,`create_user`,`update_user`,`sort`) VALUES ('3','user','用户管理','users','/sys/user','1','1',NULL,NULL,NULL,NULL,NULL,2);
INSERT INTO `` (`ID`,`code`,`name`,`permission`,`url`,`parent_id`,`type`,`description`,`create_date`,`update_date`,`create_user`,`update_user`,`sort`) VALUES ('4','root','角色管理','role','/sys/role','1','1',NULL,NULL,NULL,NULL,NULL,3);
INSERT INTO `` (`ID`,`code`,`name`,`permission`,`url`,`parent_id`,`type`,`description`,`create_date`,`update_date`,`create_user`,`update_user`,`sort`) VALUES ('5','log','日志管理','log','/log','0','1',NULL,NULL,NULL,NULL,NULL,2);
INSERT INTO `` (`ID`,`code`,`name`,`permission`,`url`,`parent_id`,`type`,`description`,`create_date`,`update_date`,`create_user`,`update_user`,`sort`) VALUES ('6','sysLog','操作日志','syslogs','/sys/logs','5','1',NULL,NULL,NULL,NULL,NULL,1);
INSERT INTO `` (`ID`,`code`,`name`,`permission`,`url`,`parent_id`,`type`,`description`,`create_date`,`update_date`,`create_user`,`update_user`,`sort`) VALUES ('dd2e0096c148414aa2c6cdd4d8a8ba86',NULL,'string',NULL,'string','string','1',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO `` (`ID`,`code`,`name`,`permission`,`url`,`parent_id`,`type`,`description`,`create_date`,`update_date`,`create_user`,`update_user`,`sort`) VALUES ('fbcfb3162e8447c3b8dfdf2a2d2b4fd1','testcode','测试新增按钮','test:add','/test/url','1','2','测试数据',NULL,NULL,NULL,NULL,NULL);


/*
-- Query: SELECT * FROM ofs.sys_log
LIMIT 0, 1000

-- Date: 2020-03-25 13:59
*/
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('01218ba56e754143b3074b10a6c8bce3',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308154138',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('196d4b26ff0e4c07b7bdd7d86e024dcc',NULL,NULL,'获取当前用户信息','127.0.0.1','0','/api/current','[]','POST','com.ofs.sys.web.controller.AccountController.current()','20200308194141',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('1ca6d6d588fb4d088ed70af41d5ce224',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308193737',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('22d58261859e417d8f0f2be5e68b7c52',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308190426',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('244626ca17f14c36b1e98bb67fc5c622',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220173445',NULL,'0',NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('2703c5355f694d40a6ad00818509f830',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308165350',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('2ac9044e64ca4037bbcece45ab440253',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308175118',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('2c6c35b788514ac6a5acc21f41cda867',NULL,NULL,'获取当前用户信息','127.0.0.1','0','/api/current','[]','POST','com.ofs.sys.web.controller.AccountController.current()','20200308194814',NULL,'db046f8f5bc5475296982002c5613f25',NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('312aa0011f744c6f9958d41a381641c2',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220161429',NULL,'0',NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('339e30302181462c8a96f7939c9edf4f',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308174844',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('388eca71f0f54543b194495cac93df4e',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308164709',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('38b90afe3d4a4c5fa1eb7cddaa23b83d',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308170221',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('3990b2571eed4b05abf86d070aa8237a',NULL,NULL,'登录','127.0.0.1','0','/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308182209',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('3f79853ecc1d44b9b068a80789f061b7',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308193526',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('443bf2fccf5947ba82634935aeb19c05',NULL,NULL,'登录','127.0.0.1','0','/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308182018',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('4b9fb00c8c7846e493f30b1532fc4704',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308172036',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('4e2b72ad7bbb4692b9cad8a05125e78b',NULL,NULL,'登录','127.0.0.1','0','/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308181856',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('62f6d3bda377405e947b5055ecbb445e',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220150010',NULL,'0',NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('630b6dd09a9247cb8f99f71732a183b1',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220174342',NULL,'0',NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('7929da139c9549eeb4d13e333391af46',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308194032',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('7c95836110de4c1994d0c290526df7ab',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308164040',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('822e038be41c4d76956c497821370628',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220174238',NULL,'0',NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('884e32320ab74d489afb41179e6c0f67',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220173941',NULL,'0',NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('8aa450857f0e483ebb8886a69109e087',NULL,NULL,'登录','127.0.0.1','0','/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308181734',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('8f019fe430944397b9a7c7888cc32913',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308181348',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('abcb28b976104302aaad5446c99e2c50',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308193408',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('ae41984e546a4720905c3c912f746e76',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308191108',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('aeac8dc215ab4369b93cf8963893896c',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308194729',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('b0915e4681d64e2c96fbf36b806df647',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308175433',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('bf9aa83aa78b4bcbab2a5e6a0c32a1ba',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308161351',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('c4a5a7372ebf48d59cd45d0ee9173708',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308174148',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('d18bd044bea24766881f40a311fd068a',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308181311',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('d70b398bd989466cba9af2ecd3b4bc42',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308182439',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('d8b182f0ca03471b88b59c620361b094',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220151045',NULL,'0',NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('d9518fd1f42141a4b81aa09c6e428e97',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308170447',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('deaafb7059c2407795960ca172cffbb8',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220174736',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('e5db4115ac2f4719b1914bd272927ca8',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220174039',NULL,'0',NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('effca00c43884623a61d69287db436d2',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220172933',NULL,'0',NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('f63ce2b01a8d49dfa99a119149a72d64',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220174723',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('f76cac949b7145bf9a35abd3b7ceb8d6',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308170358',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('fa458030da8b40b6805a22e97f81b808',NULL,NULL,'登录','127.0.0.1','0','/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200308182145',NULL,NULL,NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('fc6b4ab5cefb4ba283e924a70c5f55d0',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220172835',NULL,'0',NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('fd0dc2275f5f49f78b228885ca1b1a43',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220161528',NULL,'0',NULL);
INSERT INTO `` (`ID`,`menu_id`,`type`,`content`,`ip`,`ajax`,`uri`,`params`,`http_method`,`class_method`,`create_date`,`update_date`,`create_user`,`update_user`) VALUES ('fda23dea0a2b441d9b552fd3d17594c1',NULL,NULL,'登录','127.0.0.1','0','/api/login','[{\"account\":\"admin\",\"password\":\"******\",\"terminal\":\"PC\"}]','POST','com.ofs.sys.web.controller.AccountController.signIn()','20200220174723',NULL,NULL,NULL);
